#!/usr/bin/env bash
set -Eeuo pipefail

PORT="${1:-}"
RUNTIME_DIR="${GAME_VIDEO_RUNTIME_DIR:-/home/deploy/game-video-runtime}"
UPSTREAM_FILE="${GAME_VIDEO_NGINX_UPSTREAM_FILE:-/etc/nginx/conf.d/game-video-tool-upstream.inc}"

fail() {
  printf 'FAILED\nreason: %s\n' "$1" >&2
  exit 1
}

case "${PORT}" in
  57991|57992) ;;
  *) fail "unsupported backend port: ${PORT}; allowed ports are 57991 and 57992" ;;
esac

command -v nginx >/dev/null 2>&1 || fail "nginx not found"
curl -fsS --max-time 3 "http://127.0.0.1:${PORT}/health" >/dev/null \
  || fail "candidate backend is not healthy on port ${PORT}"

mkdir -p "${RUNTIME_DIR}"
tmp_file="$(mktemp "${UPSTREAM_FILE}.XXXXXX")"
trap 'rm -f "${tmp_file}"' EXIT

cat > "${tmp_file}" <<EOF
# Generated by game-video-switch-upstream.sh. Do not edit by hand.
set \$game_video_backend http://127.0.0.1:${PORT};
EOF

install -o root -g root -m 0644 "${tmp_file}" "${UPSTREAM_FILE}"
nginx -t
nginx -s reload

printf '%s\n' "${PORT}" > "${RUNTIME_DIR}/active-port"

printf 'SUCCESS\n'
printf 'active_port: %s\n' "${PORT}"
printf 'upstream_file: %s\n' "${UPSTREAM_FILE}"
