from __future__ import annotations


def get_all_video_model_specs() -> list[dict]:
    """Return the full known model catalog, independent of configured API keys."""
    return [
        {"id": "seedance-2.0", "name": "Seedance 2.0", "provider": "jimeng",
         "supports_ref_video": True, "supports_ref_images": True, "min_duration": 4, "max_duration": 15,
         "max_ref_images": 9, "max_ref_videos": 3, "ref_video_duration_limit": 15.2,
         "supported_resolutions": ["720p", "1080p"], "default_resolution": "720p",
         "limit_note": "生成时长 4-15 秒；支持 720P/1080P；参考视频/高级视频编辑参考视频需 15.2 秒以内",
         "supported_modes": ["generate", "reference_video", "advanced_video", "motion_transfer"],
         "price_per_second": 1.0, "price_unit": "CNY", "price_resolution_multiplier_1080p": 2.25,
         "price_note": "官方按输出视频像素、帧率、时长折算 token 计费；1080P 约为 720P 的 2.25 倍"},
        {"id": "seedance-2.0-fast", "name": "Seedance 2.0 Fast", "provider": "jimeng",
         "supports_ref_video": True, "supports_ref_images": True, "min_duration": 4, "max_duration": 10,
         "max_ref_images": 9, "max_ref_videos": 3, "ref_video_duration_limit": 15.2,
         "supported_resolutions": ["720p"], "default_resolution": "720p",
         "limit_note": "生成时长 4-10 秒；Fast 仅开放 720P；参考视频/高级视频编辑参考视频需 15.2 秒以内",
         "supported_modes": ["generate", "reference_video", "advanced_video"],
         "price_per_second": 0.8, "price_unit": "CNY"},
        {"id": "seedance-1.5-pro", "name": "Seedance 1.5 Pro", "provider": "jimeng",
         "supports_ref_video": False, "supports_ref_images": True, "min_duration": 4, "max_duration": 12,
         "max_ref_images": 2,
         "supported_resolutions": ["720p"], "default_resolution": "720p",
         "limit_note": "生成时长 4-12 秒；支持 1 张首帧图或 2 张首尾帧图；不支持参考视频/普通多参考图；当前仅开放 720P",
         "supported_modes": ["generate"],
         "price_per_second": 0.3, "price_unit": "CNY"},
        {"id": "viduq3-pro", "name": "VIDU Q3 Pro", "provider": "vidu",
         "supports_ref_video": False, "supports_ref_images": True, "min_duration": 1, "max_duration": 16,
         "max_ref_images": 1,
         "supported_resolutions": ["720p"], "default_resolution": "720p",
         "supported_modes": ["generate"],
         "price_per_second": 0.95, "price_unit": "CNY"},
        {"id": "viduq3-turbo", "name": "VIDU Q3 Turbo", "provider": "vidu",
         "supports_ref_video": False, "supports_ref_images": True, "min_duration": 1, "max_duration": 16,
         "max_ref_images": 1,
         "supported_resolutions": ["720p"], "default_resolution": "720p",
         "supported_modes": ["generate"],
         "price_per_second": 0.45, "price_unit": "CNY"},
        {"id": "happyhorse-1.0-t2v", "name": "HappyHorse 1.0 文生视频", "provider": "happyhorse",
         "supports_ref_video": False, "supports_ref_images": False, "min_duration": 3, "max_duration": 15,
         "supported_resolutions": ["720p", "1080p"], "default_resolution": "720p",
         "limit_note": "生成时长 3-15 秒；不需要参考图/参考视频",
         "supported_modes": ["generate"],
         "price_per_second": 0.9, "price_unit": "CNY",
         "price_per_second_1080p": 1.6, "price_note": "官方价格：720P 0.9元/秒，1080P 1.6元/秒"},
        {"id": "happyhorse-1.0-i2v", "name": "HappyHorse 1.0 首帧图生视频", "provider": "happyhorse",
         "supports_ref_video": False, "supports_ref_images": True, "min_duration": 3, "max_duration": 15,
         "min_ref_images": 1, "max_ref_images": 1,
         "supported_resolutions": ["720p", "1080p"], "default_resolution": "720p",
         "limit_note": "生成时长 3-15 秒；必须且只能使用 1 张首帧参考图；不支持参考视频",
         "supported_modes": ["generate"],
         "price_per_second": 0.9, "price_unit": "CNY",
         "price_per_second_1080p": 1.6, "price_note": "官方价格：720P 0.9元/秒，1080P 1.6元/秒"},
        {"id": "happyhorse-1.0-r2v", "name": "HappyHorse 1.0 参考图生视频", "provider": "happyhorse",
         "supports_ref_video": False, "supports_ref_images": True, "min_duration": 3, "max_duration": 15,
         "min_ref_images": 1, "max_ref_images": 9,
         "supported_resolutions": ["720p", "1080p"], "default_resolution": "720p",
         "limit_note": "生成时长 3-15 秒；支持 1-9 张角色/场景参考图；不支持参考视频",
         "supported_modes": ["generate"],
         "price_per_second": 0.9, "price_unit": "CNY",
         "price_per_second_1080p": 1.6, "price_note": "官方价格：720P 0.9元/秒，1080P 1.6元/秒"},
        {"id": "happyhorse-1.0-video-edit", "name": "HappyHorse 1.0 视频编辑", "provider": "happyhorse",
         "supports_ref_video": True, "supports_ref_images": True, "min_duration": 3, "max_duration": 15,
         "max_ref_images": 5, "max_ref_videos": 1, "ref_video_duration_min": 3, "ref_video_duration_limit": 60,
         "supported_resolutions": ["720p", "1080p"], "default_resolution": "720p",
         "limit_note": "输出视频最长 15 秒；输入参考视频需 3-60 秒；最多 1 个参考视频，可叠加 0-5 张参考图",
         "supported_modes": ["reference_video", "advanced_video"],
         "price_per_second": 0.9, "price_unit": "CNY",
         "price_per_second_1080p": 1.6, "price_billing": "input_output",
         "price_note": "官方价格：720P 0.9元/秒，1080P 1.6元/秒；视频编辑按输入视频与输出视频分别计费"},
        {"id": "veo3.1-fast", "name": "Veo 3.1 Fast", "provider": "toapis",
         "supports_ref_video": False, "supports_ref_images": True, "min_duration": 8, "max_duration": 8,
         "max_ref_images": 3, "supported_aspect_ratios": ["16:9", "9:16"],
         "supported_resolutions": ["720p"], "default_resolution": "720p",
         "limit_note": "ToAPIs Veo 3.1 固定生成 8 秒，支持 16:9 / 9:16，可选公网参考图 URL。",
         "supported_modes": ["generate"], "price_unit": "ToAPIs"},
        {"id": "veo3.1-lite", "name": "Veo 3.1 Lite", "provider": "toapis",
         "supports_ref_video": False, "supports_ref_images": True, "min_duration": 8, "max_duration": 8,
         "max_ref_images": 3, "supported_aspect_ratios": ["16:9", "9:16"],
         "supported_resolutions": ["720p"], "default_resolution": "720p",
         "limit_note": "ToAPIs Veo 3.1 固定生成 8 秒，支持 16:9 / 9:16，可选公网参考图 URL。",
         "supported_modes": ["generate"], "price_unit": "ToAPIs"},
        {"id": "veo3.1-quality", "name": "Veo 3.1 Quality", "provider": "toapis",
         "supports_ref_video": False, "supports_ref_images": True, "min_duration": 8, "max_duration": 8,
         "max_ref_images": 3, "supported_aspect_ratios": ["16:9", "9:16"],
         "supported_resolutions": ["720p"], "default_resolution": "720p",
         "limit_note": "ToAPIs Veo 3.1 固定生成 8 秒，支持 16:9 / 9:16，可选公网参考图 URL。",
         "supported_modes": ["generate"], "price_unit": "ToAPIs"},
    ]


def get_video_model_spec(model: str) -> dict:
    return next((item for item in get_all_video_model_specs() if item.get("id") == model), {})


def get_video_model_specs(provider_filter=None) -> list[dict]:
    """Return catalog specs, optionally filtered to configured providers."""
    if provider_filter is None:
        return get_all_video_model_specs()
    providers = {provider for provider in provider_filter if provider}
    return [item for item in get_all_video_model_specs() if item.get("provider") in providers]
